"""generation_header.py のテスト"""

from src.core.converters.generation_header import (
    generate_python_header,
    generate_yaml_header,
)


class TestGeneratePythonHeader:
    """generate_python_header 関数のテスト"""

    def test_with_full_header(self) -> None:
        """完全なヘッダーが生成されることを確認"""
        header = generate_python_header(
            "docs/pylay/users/types.lay.yaml",
            add_header=True,
            include_source=True,
        )

        assert '"""' in header
        assert "pylay自動生成ファイル" in header
        assert "このファイルを直接編集しないでください" in header
        assert "次回の pylay types 実行時に削除・再生成されます" in header
        assert "Generated by: pylay types docs/pylay/users/types.lay.yaml" in header
        assert "Source: docs/pylay/users/types.lay.yaml" in header
        assert "Generated at:" in header

    def test_with_no_header(self) -> None:
        """ヘッダーなしで空文字列が返されることを確認"""
        header = generate_python_header(
            "docs/pylay/users/types.lay.yaml",
            add_header=False,
        )
        assert header == ""

    def test_without_source_path(self) -> None:
        """ソースパスなしのヘッダーが生成されることを確認"""
        header = generate_python_header(
            "docs/pylay/users/types.lay.yaml",
            add_header=True,
            include_source=False,
        )

        assert "pylay自動生成ファイル" in header
        assert "Generated by:" not in header
        assert "Source:" not in header
        assert "Generated at:" not in header


class TestGenerateYamlHeader:
    """generate_yaml_header 関数のテスト"""

    def test_with_full_header(self) -> None:
        """完全なヘッダーが生成されることを確認"""
        header = generate_yaml_header(
            "users/types.lay.py",
            add_header=True,
            include_source=True,
        )

        assert "# ====================================" in header
        assert "# pylay自動生成ファイル" in header
        assert "# このファイルを直接編集しないでください" in header
        assert "# 次回の pylay yaml 実行時に削除・再生成されます" in header
        assert "# Generated by: pylay yaml users/types.lay.py" in header
        assert "# Source: users/types.lay.py" in header
        assert "# Generated at:" in header

    def test_with_no_header(self) -> None:
        """ヘッダーなしで空文字列が返されることを確認"""
        header = generate_yaml_header(
            "users/types.lay.py",
            add_header=False,
        )
        assert header == ""

    def test_without_source_path(self) -> None:
        """ソースパスなしのヘッダーが生成されることを確認"""
        header = generate_yaml_header(
            "users/types.lay.py",
            add_header=True,
            include_source=False,
        )

        assert "# pylay自動生成ファイル" in header
        assert "# Generated by:" not in header
        assert "# Source:" not in header
        assert "# Generated at:" not in header
